services:
  db:
    image: mysql:latest
    container_name: db1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jouw-wachtwoord
      MYSQL_DATABASE: jouw-database
      MYSQL_USER: jouw-gebruiker
      MYSQL_PASSWORD: jouw-gebruikerswachtwoord
    volumes:
      - Data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 85:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: jouw-wachtwoord

volumes:
 Data:
