version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"  # Web interface
      - "222:22"      # SSH access
    volumes:
      - gitea_data:/data  # Mount the named volume for persistence
    networks:
      - gitea_net

networks:
  gitea_net:
    driver: bridge

volumes:
  gitea_data:
    driver: local  # This tells Docker to use the default local driver for the volume
